CREATE SCHEMA postgis;

GRANT USAGE ON SCHEMA postgis TO dhis;
ALTER DEFAULT PRIVILEGES IN SCHEMA postgis GRANT SELECT ON TABLES TO dhis;
ALTER DEFAULT PRIVILEGES IN SCHEMA postgis GRANT USAGE, SELECT ON SEQUENCES TO dhis;
ALTER DEFAULT PRIVILEGES IN SCHEMA postgis GRANT EXECUTE ON FUNCTIONS TO dhis;

CREATE EXTENSION postgis WITH SCHEMA postgis;

ALTER DATABASE dhis2 SET search_path TO public,postgis;
